# deploy main branch

name: deploy-to-prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE

jobs:
  deploy:
    name: Deploy to prod env
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt --upgrade pip
      - name: Generate from templates
        run: python generate_sites.py
      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST_IP }}
          ssh-port: ${{ secrets.SSH_HOST_PORT }}
      - name: Update download script with rsync
        run: |
          rsync --verbose -e "ssh -p ${{ secrets.SSH_HOST_PORT }}" ./download_data.py ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }}:/opt/scripts/download_data.py
      - name: Deploy site with rsync
        run: |
          rsync --verbose --recursive --delete --exclude "data" -e "ssh -p ${{ secrets.SSH_HOST_PORT }}" \
            ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }}:/var/www/html/
